### ISSUE TITLE
.zarr conversion improvements to make

### ISSUE THREAD

**Issue by vreuter** [gerlichlab/looptrace#163]
- [ ] paralellisation #157 
- [ ] code reuse: currently `convert_datasets_to_zarr.py` doesn't reuse code from `image_io.images_to_ome_zarr`
- [ ] positions could be inferred like in `image_io.stack_nd2_to_dask` and `image_io.stack_tif_to_dask`, and `zarr_conversions` could be parsed directly from config, obviating the need for building an `ImageHandler`
- [ ] functions should be renamed: `one_to_one` should be come `workflow` and `workflow` should become something like `process_single_subfolder`; update `run_processing_pipeline.py` to reflect this 
- [ ] `input_folders` parameter on what's now `workflow` should become singular in name and in type
