### ISSUE TITLE
Changes to locus spot visualisation

### ISSUE THREAD

**Issue by vreuter** [gerlichlab/looptrace#402]
- [ ] sort properly the CSVs which encode the points -- can be deferred to the plugin
- [x] generate the visualisation per (FOV, trace structure) combination--rather than just per FOV--when we're "merging" spots for tracing (#279 )
- [x] Track reindexed (contiguous integer sequence starting from 0) trace ID per visualisation unit (depends on second item) -- https://github.com/gerlichlab/looptrace/issues/407
- [x] Trace reindexed locus timepoints () for each locus spot viewing unit -- https://github.com/gerlichlab/looptrace/issues/406
